// Generated by CoffeeScript 1.3.3
(function() {
  var Melange;

  Melange = (function() {
    var _ref;

    function Melange() {}

    if ((_ref = Melange.host) == null) {
      Melange.host = location.hostname;
    }

    Melange.init = function() {
      if (typeof mixpanel === "undefined" || mixpanel === null) {
        return;
      }
      if (typeof user !== "undefined" && user !== null) {
        return mixpanel.people.identify(user);
      }
    };

    Melange.log = function() {
      if (window.console) {
        return console.log.apply(console, arguments);
      }
    };

    Melange.report = function(action, subject, meta) {
      if (meta == null) {
        meta = {};
      }
      if (typeof mixpanel === "undefined" || mixpanel === null) {
        return;
      }
      if (this.debug) {
        return this.log("Melange.report", action, subject, meta);
      } else {
        return mixpanel.track("" + action + " " + subject, meta);
      }
    };

    Melange.reportView = function(subject, meta) {
      return this.report("viewed", [this.host, subject].join(""), meta);
    };

    return Melange;

  })();

  window.Melange = Melange;

}).call(this);
